version: '3.1'

services:

  mongo:
    image: mongo:4.4.4
    restart: always
    container_name: guess-albom-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: guess-albom
    ports:
      - 27017:27017
    volumes:
      - $PWD/mongo